language: cpp

sudo: enabled

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
    env:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
- eval "${MATRIX_EVAL}"
- mkdir build && cd build
- CMAKE_RELEASE_NAME=cmake-3.8.2-Linux-x86_64
- wget https://cmake.org/files/v3.8/${CMAKE_RELEASE_NAME}.tar.gz
- tar -xf ${CMAKE_RELEASE_NAME}.tar.gz
- CMAKE=`pwd`/${CMAKE_RELEASE_NAME}/bin/cmake
- CTEST=`pwd`/${CMAKE_RELEASE_NAME}/bin/ctest

script:
- "${CMAKE} -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5
  .."
- make
- "${CTEST}"

before_deploy:
- APP_PATH="`pwd`/src/app"
- mv ${APP_PATH}/poly-calc-app ${APP_PATH}/poly-calc-app-linux-x64

deploy:
  provider: releases
  api_key:
    secure: bFLWhmvKuMHCqFDBVktNApotMEM1bGWIzXuo7NsgjS/bOE/rGbEOzQqVFT3dYshrVorN6gMGQKY4dWTXF0lXhGRUEdEhWh/0ozwjoM2bQwdwR7YyR6treq1VuZ9XbTbOTyetAwl1vplfhVbyFw9uyZSHuhCq1WGEpZ5hPrCOA2b5faq3Acxr0OCPbsscwApWtqdwOzRyF7I2ZW5q7nniKVhLZas9GCdO//98s66N6hCsHDeZXaZJkj78+urTZKN2b0jk6fR5zfmEjGJlPgNsHahbifDO5gQrtT0u/btN0Qu+lZj+aXOXdSC0xedI0l+LdOt3CzZa0XInDvfJK78KuW5GGTpRAvCrwZsMuYlyVh05Vc0pTCzUknprNrKIGqDk/zFqTvzqAGSrG3e1w2J0CR0Mtx5+SBYnK78G5shwhuGsLbwYQY2DLkPfNmq7iMCeiaTiV7LUm4iKJL6sH83HnBwww8yaT+zjxxnpuINLkM+znW4z3BoaZDcy2Gsvm6AscIauUHTQJnEAsVaBkEO/ZUpP/XM55FEU2e1m2QHAoslQTZZ8GoH5bSo5XqoXcWoVv91YNQ0P35FMvd/EKwd/bp3uvd7Sgj3jTwKitvR8pYuNQMm3p4QFIoOcfZ3G3T/TlJOUo1L+Nq0gQYS5r9bdampJg87OYOQ3G2S4yRz2+Jw=
  file: "${APP_PATH}/poly-calc-app-linux-x64"
  skip_cleanup: true
  on:
    tags: true
    repo: zelinf/poly-calc
