language: cpp

sudo: enabled

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
  - eval "${MATRIX_EVAL}"
  - CMAKE_RELEASE_NAME=cmake-3.8.2-Linux-x86_64
  - wget https://cmake.org/files/v3.8/${CMAKE_RELEASE_NAME}.tar.gz
  - tar -xf ${CMAKE_RELEASE_NAME}.tar.gz
  - ln -s ${CMAKE_RELEASE_NAME}/bin/* /usr/local/bin

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - ctest
