language: cpp

sudo: enabled

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

# Install tools
before_install:
  - eval "${MATRIX_EVAL}"
  - mkdir build && cd build
  - CMAKE_RELEASE_NAME=cmake-3.8.2-Linux-x86_64
  - wget https://cmake.org/files/v3.8/${CMAKE_RELEASE_NAME}.tar.gz
  - tar -xf ${CMAKE_RELEASE_NAME}.tar.gz
  - CMAKE=`pwd`/${CMAKE_RELEASE_NAME}/bin/cmake
  - CTEST=`pwd`/${CMAKE_RELEASE_NAME}/bin/ctest

# Build the project
script:
  - ${CMAKE} -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 ..
  - make
  - ${CTEST}

before_deploy:
  - APP_PATH="`pwd`/src/app/poly-calc-app"
  - GITHUB_API_KEY="fWxBhQd1rStcJwOA3gy70BGPxzLzMvlU5afbolhgRw2RceGMaKD+fQGGRnWa5RgYgoOTco3zXyuJPy/2yxYh2866u2oGzJsyk9CpmvUL60Wh8t03uEsHth9CdIPWcMZkVMsjZtJ837VMpBVmKqbHiDGs+CWEoBXq/l51n5Bri4bW5B7SVXwDtPTkj49FQFo03iAQBc08JiV7Gan7pijOTVmVxvJajtj9N5a57GpB8j9q/VQHHL3RriNr6ja514WOXcLOyeQepRSpSDfaYCM5y7DJ4fLy3fqcKdHG1O7JZbGYCCbT+TOs1E5PsUlfc3qeSIdzRPhmdti/EkBW+LeoO33JKdB9gmSbZ9WKwS9zlGgJwD6+8pmyzWf4lFB/G7eAX9Av2G5g/AMJhP0XV4LjLCQqlo5FsYvH5+r83nySO/1SKHfqCMqnkP2rMqj9Qk3rzegYveLMA7Wc9Z8Vl5iAP10F5uQSCBZ+3EBy36D+lGhAMnvynw1zVVAwGW7vXvny2yWKPgznMs6dEj2WfTQQL6VRgWdGclsyBWrvavTxY+zYXznpBYL15yDVBm38UF3TjE1aS3IFhs/1mPeM4fiUHIf1OBilBrxQ1Gxa0lg+vFD2qkFus6hldMcA3u/ihDunpWLb/pjbhKKIZbrYxalnx05kNeOUsO9DInVCAbbzLc8="

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_API_KEY}
  file: ${APP_PATH}
  skip_cleanup: true
  on:
    tags: true
