
# ---------------------------
# General Configuration
# ---------------------------

version: 0.1.{build}-{branch}

skip_tags: false
skip_non_tags: false

max_jobs: 1

# ---------------------------
# Environment
# ---------------------------

image: Visual Studio 2015

init:
  - git config --global core.autocrlf true
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

clone_depth: 1
environment:
  APPVEYOR_RDP_PASSWORD: Ufida2017!

platform:
  - Win32

configuration:
  - Release

build:
  parallel: true
  project: build/ALL_BUILD.vcxproj
  verbosity: normal

before_build:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 14 2015" ..

#
# Tests
#

test_script:
  - ctest

#
# After
#

#artifacts:
#  - path: build/src/app-cli/Release/bank-calling-app.exe
#    name: bank-calling-app
#    type: File

# Deployment
#deploy:
#  release: bank-calling-v$(appveyor_build_version)
#  description: 'A bank-calling simulation program'
#  provider: GitHub
#  auth_token:
#    secure: wCLCNSQ1gr1PWkBxxhfkeTdWCjdmChy3C/yl0w0iYCB6OThAnJZWUHL442xj77yd
#  artifact: bank-calling-app
#  draft: false
#  prerelease: false
#  on:
#    branch:
#      - master
#      - v0.3.2
#    appveyor_repo_tag: true