
# ---------------------------
# General Configuration
# ---------------------------

version: 0.1.{build}-{branch}

skip_tags: false
skip_non_tags: false

max_jobs: 1

# ---------------------------
# Environment
# ---------------------------

image: Visual Studio 2015

init:
  - git config --global core.autocrlf true
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

clone_depth: 1
environment:
  APPVEYOR_RDP_PASSWORD: Ufida2017!

platform:
  - Win32
  - x64

configuration:
  - Release

build:
  parallel: true
  project: build/ALL_BUILD.vcxproj
  verbosity: normal

before_build:
  - mkdir build
  - cd build
  - 'cmake -DCMAKE_GENERATOR_PLATFORM=%PLATFORM% ..'

after_build:
  - 'ren %APPVEYOR_BUILD_FOLDER%\build\src\app\Release\poly-calc-app.exe poly-calc-app-%PLATFORM%.exe'

#
# Tests
#

test_script:
  - ctest

#
# After
#

artifacts:
  - path: build/src/app/Release/poly-calc-app-{platform}.exe
    name: poly-calc-app
    type: File

# Deployment
deploy:
  - provider: GitHub
    release: poly-calc-{branch}
    description: 'A simple polynomial calculator'
    auth_token:
      secure: wCLCNSQ1gr1PWkBxxhfkeTdWCjdmChy3C/yl0w0iYCB6OThAnJZWUHL442xj77yd
    artifact: poly-calc-app
    draft: true
    prerelease: false
    on:
      branch: /v\d\.\d\.\d/
      appveyor_repo_tag: true

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))